// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgXhS0QM-2vFcCNRb0zdgIsy6kdJCX4uI',
    appId: '1:346673768724:web:a6c42d62d81d9848c6fa01',
    messagingSenderId: '346673768724',
    projectId: 'r0cktheman',
    authDomain: 'r0cktheman.firebaseapp.com',
    storageBucket: 'r0cktheman.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTFQHWElMo8nNEfCJNEsFdeNS7TFeYQt8',
    appId: '1:346673768724:android:1ecbedfd5acf4c7cc6fa01',
    messagingSenderId: '346673768724',
    projectId: 'r0cktheman',
    storageBucket: 'r0cktheman.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6sfxhWLCbRavvh5SbJ5NhtxZ6kAq1S0E',
    appId: '1:346673768724:ios:951f3fd6cbe02719c6fa01',
    messagingSenderId: '346673768724',
    projectId: 'r0cktheman',
    storageBucket: 'r0cktheman.appspot.com',
    androidClientId: '346673768724-31rtifooagq0bju303l7oprkhnkukgtn.apps.googleusercontent.com',
    iosClientId: '346673768724-fbjo7k9ebe9baq631jp72lp5mk271paq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireBase',
  );
}
